#<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
#$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
#<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>


Fibonacci =[1,2]
Summe = 0

while Fibonacci[len(Fibonacci)-1] < 4000000 :
    Fibonacci.append(Fibonacci[len(Fibonacci)-1]+Fibonacci[len(Fibonacci)-2])

for x in Fibonacci:
    if x%2 == 0:
        Summe += x

#print(Fibonacci)
print(Summe)