#<p>The sequence of triangle numbers is generated by adding the natural numbers. So the $7$<sup>th</sup> triangle number would be $1 + 2 + 3 + 4 + 5 + 6 + 7 = 28$. The first ten terms would be:
#$$1, 3, 6, 10, 15, 21, 28, 36, 45, 55, \dots$$</p>
#<p>Let us list the factors of the first seven triangle numbers:</p>
#\begin{align}
#\mathbf 1 &amp;\colon 1\\
#\mathbf 3 &amp;\colon 1,3\\
#\mathbf 6 &amp;\colon 1,2,3,6\\
#\mathbf{10} &amp;\colon 1,2,5,10\\
#\mathbf{15} &amp;\colon 1,3,5,15\\
#\mathbf{21} &amp;\colon 1,3,7,21\\
#\mathbf{28} &amp;\colon 1,2,4,7,14,28
#\end{align}
#<p>We can see that $28$ is the first triangle number to have over five divisors.</p>
#<p>What is the value of the first triangle number to have over five hundred divisors?</p>

divs = 500
num = 1
i = 2

def get_divs(num):
    count = 0
    sqrt_n = int(num**0.5)
    for x in range(1,sqrt_n+1):
        if num%x==0:
            count +=2
        if sqrt_n * sqrt_n == num:
            count -= 1
        if count > divs:
            return True
    return False

while get_divs(num) == False:
    print(f"candidate: {num}")
    num += i 
    i += 1
print(f"Triangular winner: {num}")